apiVersion: v1
kind: Secret
metadata:
  name: cluster1-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: cluster1
  server: https://api.acidonpe92.sandbox1915.opentlc.com:6443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImhQVzdzWXdscmZRdzczV0JUTHdNMXE5bThYaHdOeXBoZk0tVC1kOEN3b2MifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Ims4c2FkbWluLXRva2VuLWxtejljIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Ims4c2FkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZTBjZmE0NGYtMTJlOS00ZGI0LTk2YzgtN2YyNzY3YjVmNDgwIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6azhzYWRtaW4ifQ.EIM4utid4GiJctfe5ZB-79z3an1VChiCSLVw2I9ga6mPQfChAdknGvnunDF5hamrfRkXxE9LjPGfylAaMy2TT71VXn9QFHs6CcBeF02SNJzVck0a62936kNcvZSz_GsuFJy8BrX__dktTI0P199fsuOTtKkoALuvzErwm1fwxTqnIOL-VTMUGJq_aWOIysA2681W60_zjvqtRWOYVDgAdKDGnKeogW7boPjwBc-02crXHhxBTmvG9abz7-wHXIWF5ePPFIEeBGCOUYAsssZBBAlICIRMsawLG0Kb5EqRgeUGuXf64PLdEFx2T-2kCKquFHRyS_VO8PJ3sCXTTV2XPm5z7AcxJUJofEuTPZLAlQUpV88X8XC5xGjVvbDDbJZtkeLDd4ogxEaC88N2Y_-MwxIoHaOd8lLZCKBVSIvdwKYNnhVDrf1vvbHRydl4xhA1lSG8VPxe_n-eSnr1ZuPu_Vql1RS0MHPcpWADVG69P6VYO6j9ZG3cDnLwIHRMxeral7tGYJ8rHewsrm9-TfEHVWKg-CPOPlgNk_O0poMnLeIWF3DtMtbi5BD4VQnsoqF4SHEQw_E3T3r0KgX8RF9MFDvTPtzXscUNRf2bkaMpJZjlrv92XheXMOgD-GUwjk6M1_ZVEGd6Y-EdRQ0sE0GeNuohWap7I-OWT_uW5duXz9o",
      "tlsClientConfig": {
        "insecure": true
      }
    }