{{- range $key, $val := $.Values.environments }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}-onboarding
spec:
  project: default
  destination:
    name: ''
    namespace: openshift-gitops
    server: {{ $val.k8sapi }}
  source:
    path: .
    repoURL: 'https://github.com/autstudent/module-onboarding.git'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $key }}-modules
spec:
  generators:
  - list:
      elements:
      {{- range $keymod, $valmod := $val.modules }}
        - cluster: {{ $val.k8sapi }}
          ns: {{ $valmod.ns }}
          name: {{ $valmod.name }}
          repo: {{ $valmod.repo }}
          path: {{ $valmod.path }}
      {{- end }}
  template:
    metadata:
      name: '{{ $key }}-{{"{{name}}"}}'
    spec:
      project: default
      source:
        repoURL: '{{"{{repo}}"}}'
        targetRevision: HEAD
        path: '{{"{{path}}"}}'
      destination:
        name: ''
        server: '{{"{{cluster}}"}}'
        namespace: '{{"{{ns}}"}}'
{{- end }}